/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordDownloadRouteImport } from './routes/record-download'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTaskExecutionsRouteImport } from './routes/_authenticated/task-executions'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedMediaRouteRouteImport } from './routes/_authenticated/media/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedMediaIndexRouteImport } from './routes/_authenticated/media/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDajialaIndexRouteImport } from './routes/_authenticated/dajiala/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAnalysisIndexRouteImport } from './routes/_authenticated/analysis/index'
import { Route as AuthenticatedAiChatIndexRouteImport } from './routes/_authenticated/ai-chat/index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsRobotRouteImport } from './routes/_authenticated/settings/robot'
import { Route as AuthenticatedSettingsPromptsRouteImport } from './routes/_authenticated/settings/prompts'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsFeishuRouteImport } from './routes/_authenticated/settings/feishu'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAsrRouteImport } from './routes/_authenticated/settings/asr'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings/ai'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedMediaTemplatesRouteImport } from './routes/_authenticated/media/templates'
import { Route as AuthenticatedMediaTagsRouteImport } from './routes/_authenticated/media/tags'
import { Route as AuthenticatedMediaPublishRouteImport } from './routes/_authenticated/media/publish'
import { Route as AuthenticatedMediaEditorRouteImport } from './routes/_authenticated/media/editor'
import { Route as AuthenticatedMediaAssetsRouteImport } from './routes/_authenticated/media/assets'
import { Route as AuthenticatedMediaArticlesRouteImport } from './routes/_authenticated/media/articles'
import { Route as AuthenticatedMediaAccountsRouteImport } from './routes/_authenticated/media/accounts'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAnalysisStaffMappingRouteImport } from './routes/_authenticated/analysis/staff-mapping'
import { Route as AuthenticatedAnalysisChatRouteImport } from './routes/_authenticated/analysis/chat'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin/pages'

const RecordDownloadRoute = RecordDownloadRouteImport.update({
  id: '/record-download',
  path: '/record-download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskExecutionsRoute =
  AuthenticatedTaskExecutionsRouteImport.update({
    id: '/task-executions',
    path: '/task-executions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaRouteRoute = AuthenticatedMediaRouteRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedMediaIndexRoute = AuthenticatedMediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMediaRouteRoute,
} as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDajialaIndexRoute =
  AuthenticatedDajialaIndexRouteImport.update({
    id: '/dajiala/',
    path: '/dajiala/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysisIndexRoute =
  AuthenticatedAnalysisIndexRouteImport.update({
    id: '/analysis/',
    path: '/analysis/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiChatIndexRoute =
  AuthenticatedAiChatIndexRouteImport.update({
    id: '/ai-chat/',
    path: '/ai-chat/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsRobotRoute =
  AuthenticatedSettingsRobotRouteImport.update({
    id: '/robot',
    path: '/robot',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPromptsRoute =
  AuthenticatedSettingsPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsFeishuRoute =
  AuthenticatedSettingsFeishuRouteImport.update({
    id: '/feishu',
    path: '/feishu',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAsrRoute =
  AuthenticatedSettingsAsrRouteImport.update({
    id: '/asr',
    path: '/asr',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedSettingsRouteRoute,
} as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedMediaTemplatesRoute =
  AuthenticatedMediaTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedMediaRouteRoute,
  } as any)
const AuthenticatedMediaTagsRoute = AuthenticatedMediaTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedMediaRouteRoute,
} as any)
const AuthenticatedMediaPublishRoute =
  AuthenticatedMediaPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => AuthenticatedMediaRouteRoute,
  } as any)
const AuthenticatedMediaEditorRoute =
  AuthenticatedMediaEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AuthenticatedMediaRouteRoute,
  } as any)
const AuthenticatedMediaAssetsRoute =
  AuthenticatedMediaAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedMediaRouteRoute,
  } as any)
const AuthenticatedMediaArticlesRoute =
  AuthenticatedMediaArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedMediaRouteRoute,
  } as any)
const AuthenticatedMediaAccountsRoute =
  AuthenticatedMediaAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedMediaRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalysisStaffMappingRoute =
  AuthenticatedAnalysisStaffMappingRouteImport.update({
    id: '/analysis/staff-mapping',
    path: '/analysis/staff-mapping',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalysisChatRoute =
  AuthenticatedAnalysisChatRouteImport.update({
    id: '/analysis/chat',
    path: '/analysis/chat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/record-download': typeof RecordDownloadRoute
  '/media': typeof AuthenticatedMediaRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/accounts': typeof AuthenticatedAccountsRoute
  '/task-executions': typeof AuthenticatedTaskExecutionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/analysis/chat': typeof AuthenticatedAnalysisChatRoute
  '/analysis/staff-mapping': typeof AuthenticatedAnalysisStaffMappingRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/media/accounts': typeof AuthenticatedMediaAccountsRoute
  '/media/articles': typeof AuthenticatedMediaArticlesRoute
  '/media/assets': typeof AuthenticatedMediaAssetsRoute
  '/media/editor': typeof AuthenticatedMediaEditorRoute
  '/media/publish': typeof AuthenticatedMediaPublishRoute
  '/media/tags': typeof AuthenticatedMediaTagsRoute
  '/media/templates': typeof AuthenticatedMediaTemplatesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/asr': typeof AuthenticatedSettingsAsrRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/feishu': typeof AuthenticatedSettingsFeishuRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/settings/robot': typeof AuthenticatedSettingsRobotRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/ai-chat': typeof AuthenticatedAiChatIndexRoute
  '/analysis': typeof AuthenticatedAnalysisIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/dajiala': typeof AuthenticatedDajialaIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/media/': typeof AuthenticatedMediaIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/record-download': typeof RecordDownloadRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/accounts': typeof AuthenticatedAccountsRoute
  '/task-executions': typeof AuthenticatedTaskExecutionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/analysis/chat': typeof AuthenticatedAnalysisChatRoute
  '/analysis/staff-mapping': typeof AuthenticatedAnalysisStaffMappingRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/media/accounts': typeof AuthenticatedMediaAccountsRoute
  '/media/articles': typeof AuthenticatedMediaArticlesRoute
  '/media/assets': typeof AuthenticatedMediaAssetsRoute
  '/media/editor': typeof AuthenticatedMediaEditorRoute
  '/media/publish': typeof AuthenticatedMediaPublishRoute
  '/media/tags': typeof AuthenticatedMediaTagsRoute
  '/media/templates': typeof AuthenticatedMediaTemplatesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/asr': typeof AuthenticatedSettingsAsrRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/feishu': typeof AuthenticatedSettingsFeishuRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/settings/robot': typeof AuthenticatedSettingsRobotRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/ai-chat': typeof AuthenticatedAiChatIndexRoute
  '/analysis': typeof AuthenticatedAnalysisIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/dajiala': typeof AuthenticatedDajialaIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/media': typeof AuthenticatedMediaIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/record-download': typeof RecordDownloadRoute
  '/_authenticated/media': typeof AuthenticatedMediaRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/task-executions': typeof AuthenticatedTaskExecutionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/analysis/chat': typeof AuthenticatedAnalysisChatRoute
  '/_authenticated/analysis/staff-mapping': typeof AuthenticatedAnalysisStaffMappingRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/media/accounts': typeof AuthenticatedMediaAccountsRoute
  '/_authenticated/media/articles': typeof AuthenticatedMediaArticlesRoute
  '/_authenticated/media/assets': typeof AuthenticatedMediaAssetsRoute
  '/_authenticated/media/editor': typeof AuthenticatedMediaEditorRoute
  '/_authenticated/media/publish': typeof AuthenticatedMediaPublishRoute
  '/_authenticated/media/tags': typeof AuthenticatedMediaTagsRoute
  '/_authenticated/media/templates': typeof AuthenticatedMediaTemplatesRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/asr': typeof AuthenticatedSettingsAsrRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/feishu': typeof AuthenticatedSettingsFeishuRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/_authenticated/settings/robot': typeof AuthenticatedSettingsRobotRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/ai-chat/': typeof AuthenticatedAiChatIndexRoute
  '/_authenticated/analysis/': typeof AuthenticatedAnalysisIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/dajiala/': typeof AuthenticatedDajialaIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/media/': typeof AuthenticatedMediaIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/record-download'
    | '/media'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/accounts'
    | '/task-executions'
    | '/'
    | '/admin/pages'
    | '/analysis/chat'
    | '/analysis/staff-mapping'
    | '/errors/$error'
    | '/media/accounts'
    | '/media/articles'
    | '/media/assets'
    | '/media/editor'
    | '/media/publish'
    | '/media/tags'
    | '/media/templates'
    | '/settings/account'
    | '/settings/ai'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/asr'
    | '/settings/display'
    | '/settings/feishu'
    | '/settings/notifications'
    | '/settings/prompts'
    | '/settings/robot'
    | '/settings/users'
    | '/ai-chat'
    | '/analysis'
    | '/apps'
    | '/chats'
    | '/dajiala'
    | '/help-center'
    | '/media/'
    | '/settings/'
    | '/tasks'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/record-download'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/accounts'
    | '/task-executions'
    | '/'
    | '/admin/pages'
    | '/analysis/chat'
    | '/analysis/staff-mapping'
    | '/errors/$error'
    | '/media/accounts'
    | '/media/articles'
    | '/media/assets'
    | '/media/editor'
    | '/media/publish'
    | '/media/tags'
    | '/media/templates'
    | '/settings/account'
    | '/settings/ai'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/asr'
    | '/settings/display'
    | '/settings/feishu'
    | '/settings/notifications'
    | '/settings/prompts'
    | '/settings/robot'
    | '/settings/users'
    | '/ai-chat'
    | '/analysis'
    | '/apps'
    | '/chats'
    | '/dajiala'
    | '/help-center'
    | '/media'
    | '/settings'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/record-download'
    | '/_authenticated/media'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/accounts'
    | '/_authenticated/task-executions'
    | '/_authenticated/'
    | '/_authenticated/admin/pages'
    | '/_authenticated/analysis/chat'
    | '/_authenticated/analysis/staff-mapping'
    | '/_authenticated/errors/$error'
    | '/_authenticated/media/accounts'
    | '/_authenticated/media/articles'
    | '/_authenticated/media/assets'
    | '/_authenticated/media/editor'
    | '/_authenticated/media/publish'
    | '/_authenticated/media/tags'
    | '/_authenticated/media/templates'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/asr'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/feishu'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/prompts'
    | '/_authenticated/settings/robot'
    | '/_authenticated/settings/users'
    | '/_authenticated/ai-chat/'
    | '/_authenticated/analysis/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/dajiala/'
    | '/_authenticated/help-center/'
    | '/_authenticated/media/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  RecordDownloadRoute: typeof RecordDownloadRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/record-download': {
      id: '/record-download'
      path: '/record-download'
      fullPath: '/record-download'
      preLoaderRoute: typeof RecordDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task-executions': {
      id: '/_authenticated/task-executions'
      path: '/task-executions'
      fullPath: '/task-executions'
      preLoaderRoute: typeof AuthenticatedTaskExecutionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/media/': {
      id: '/_authenticated/media/'
      path: '/'
      fullPath: '/media/'
      preLoaderRoute: typeof AuthenticatedMediaIndexRouteImport
      parentRoute: typeof AuthenticatedMediaRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dajiala/': {
      id: '/_authenticated/dajiala/'
      path: '/dajiala'
      fullPath: '/dajiala'
      preLoaderRoute: typeof AuthenticatedDajialaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysis/': {
      id: '/_authenticated/analysis/'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-chat/': {
      id: '/_authenticated/ai-chat/'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthenticatedAiChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/robot': {
      id: '/_authenticated/settings/robot'
      path: '/robot'
      fullPath: '/settings/robot'
      preLoaderRoute: typeof AuthenticatedSettingsRobotRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/prompts': {
      id: '/_authenticated/settings/prompts'
      path: '/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof AuthenticatedSettingsPromptsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/feishu': {
      id: '/_authenticated/settings/feishu'
      path: '/feishu'
      fullPath: '/settings/feishu'
      preLoaderRoute: typeof AuthenticatedSettingsFeishuRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/asr': {
      id: '/_authenticated/settings/asr'
      path: '/asr'
      fullPath: '/settings/asr'
      preLoaderRoute: typeof AuthenticatedSettingsAsrRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/media/templates': {
      id: '/_authenticated/media/templates'
      path: '/templates'
      fullPath: '/media/templates'
      preLoaderRoute: typeof AuthenticatedMediaTemplatesRouteImport
      parentRoute: typeof AuthenticatedMediaRouteRoute
    }
    '/_authenticated/media/tags': {
      id: '/_authenticated/media/tags'
      path: '/tags'
      fullPath: '/media/tags'
      preLoaderRoute: typeof AuthenticatedMediaTagsRouteImport
      parentRoute: typeof AuthenticatedMediaRouteRoute
    }
    '/_authenticated/media/publish': {
      id: '/_authenticated/media/publish'
      path: '/publish'
      fullPath: '/media/publish'
      preLoaderRoute: typeof AuthenticatedMediaPublishRouteImport
      parentRoute: typeof AuthenticatedMediaRouteRoute
    }
    '/_authenticated/media/editor': {
      id: '/_authenticated/media/editor'
      path: '/editor'
      fullPath: '/media/editor'
      preLoaderRoute: typeof AuthenticatedMediaEditorRouteImport
      parentRoute: typeof AuthenticatedMediaRouteRoute
    }
    '/_authenticated/media/assets': {
      id: '/_authenticated/media/assets'
      path: '/assets'
      fullPath: '/media/assets'
      preLoaderRoute: typeof AuthenticatedMediaAssetsRouteImport
      parentRoute: typeof AuthenticatedMediaRouteRoute
    }
    '/_authenticated/media/articles': {
      id: '/_authenticated/media/articles'
      path: '/articles'
      fullPath: '/media/articles'
      preLoaderRoute: typeof AuthenticatedMediaArticlesRouteImport
      parentRoute: typeof AuthenticatedMediaRouteRoute
    }
    '/_authenticated/media/accounts': {
      id: '/_authenticated/media/accounts'
      path: '/accounts'
      fullPath: '/media/accounts'
      preLoaderRoute: typeof AuthenticatedMediaAccountsRouteImport
      parentRoute: typeof AuthenticatedMediaRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysis/staff-mapping': {
      id: '/_authenticated/analysis/staff-mapping'
      path: '/analysis/staff-mapping'
      fullPath: '/analysis/staff-mapping'
      preLoaderRoute: typeof AuthenticatedAnalysisStaffMappingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysis/chat': {
      id: '/_authenticated/analysis/chat'
      path: '/analysis/chat'
      fullPath: '/analysis/chat'
      preLoaderRoute: typeof AuthenticatedAnalysisChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedMediaRouteRouteChildren {
  AuthenticatedMediaAccountsRoute: typeof AuthenticatedMediaAccountsRoute
  AuthenticatedMediaArticlesRoute: typeof AuthenticatedMediaArticlesRoute
  AuthenticatedMediaAssetsRoute: typeof AuthenticatedMediaAssetsRoute
  AuthenticatedMediaEditorRoute: typeof AuthenticatedMediaEditorRoute
  AuthenticatedMediaPublishRoute: typeof AuthenticatedMediaPublishRoute
  AuthenticatedMediaTagsRoute: typeof AuthenticatedMediaTagsRoute
  AuthenticatedMediaTemplatesRoute: typeof AuthenticatedMediaTemplatesRoute
  AuthenticatedMediaIndexRoute: typeof AuthenticatedMediaIndexRoute
}

const AuthenticatedMediaRouteRouteChildren: AuthenticatedMediaRouteRouteChildren =
  {
    AuthenticatedMediaAccountsRoute: AuthenticatedMediaAccountsRoute,
    AuthenticatedMediaArticlesRoute: AuthenticatedMediaArticlesRoute,
    AuthenticatedMediaAssetsRoute: AuthenticatedMediaAssetsRoute,
    AuthenticatedMediaEditorRoute: AuthenticatedMediaEditorRoute,
    AuthenticatedMediaPublishRoute: AuthenticatedMediaPublishRoute,
    AuthenticatedMediaTagsRoute: AuthenticatedMediaTagsRoute,
    AuthenticatedMediaTemplatesRoute: AuthenticatedMediaTemplatesRoute,
    AuthenticatedMediaIndexRoute: AuthenticatedMediaIndexRoute,
  }

const AuthenticatedMediaRouteRouteWithChildren =
  AuthenticatedMediaRouteRoute._addFileChildren(
    AuthenticatedMediaRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsAsrRoute: typeof AuthenticatedSettingsAsrRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsFeishuRoute: typeof AuthenticatedSettingsFeishuRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPromptsRoute: typeof AuthenticatedSettingsPromptsRoute
  AuthenticatedSettingsRobotRoute: typeof AuthenticatedSettingsRobotRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
    AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsAsrRoute: AuthenticatedSettingsAsrRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsFeishuRoute: AuthenticatedSettingsFeishuRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsPromptsRoute: AuthenticatedSettingsPromptsRoute,
    AuthenticatedSettingsRobotRoute: AuthenticatedSettingsRobotRoute,
    AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMediaRouteRoute: typeof AuthenticatedMediaRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedTaskExecutionsRoute: typeof AuthenticatedTaskExecutionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAnalysisChatRoute: typeof AuthenticatedAnalysisChatRoute
  AuthenticatedAnalysisStaffMappingRoute: typeof AuthenticatedAnalysisStaffMappingRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAiChatIndexRoute: typeof AuthenticatedAiChatIndexRoute
  AuthenticatedAnalysisIndexRoute: typeof AuthenticatedAnalysisIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDajialaIndexRoute: typeof AuthenticatedDajialaIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMediaRouteRoute: AuthenticatedMediaRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedTaskExecutionsRoute: AuthenticatedTaskExecutionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAnalysisChatRoute: AuthenticatedAnalysisChatRoute,
  AuthenticatedAnalysisStaffMappingRoute:
    AuthenticatedAnalysisStaffMappingRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAiChatIndexRoute: AuthenticatedAiChatIndexRoute,
  AuthenticatedAnalysisIndexRoute: AuthenticatedAnalysisIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDajialaIndexRoute: AuthenticatedDajialaIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  RecordDownloadRoute: RecordDownloadRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
